// Norman Agent integration stubs
// Real implementation will connect to Norman Agent API

export interface NormanChatRequest {
  message: string;
  context?: Record<string, unknown>;
}

export interface NormanChatResponse {
  id: string;
  response: string;
  actions: NormanAction[];
  timestamp: string;
}

export interface NormanAction {
  type: 'create_dashboard' | 'add_ticker' | 'set_preference' | 'create_condition' | 'research';
  description: string;
  parameters: Record<string, unknown>;
}

export interface NormanTask {
  id: string;
  type: string;
  status: 'pending' | 'running' | 'completed' | 'failed';
  description: string;
  result?: Record<string, unknown>;
  createdAt: string;
  completedAt?: string;
}

export interface NormanReport {
  id: string;
  title: string;
  summary: string;
  content: string;
  symbols: string[];
  createdAt: string;
}

class NormanAgent {
  async chat(request: NormanChatRequest): Promise<NormanChatResponse> {
    // Stub — returns mock response
    return {
      id: `norman-${Date.now()}`,
      response: `I understand your request: "${request.message}". Norman Agent integration is pending — this is a stub response. Once connected, I'll be able to create dashboards, analyze trades, and provide research reports.`,
      actions: [],
      timestamp: new Date().toISOString(),
    };
  }

  async createTask(type: string, description: string, params?: Record<string, unknown>): Promise<NormanTask> {
    return {
      id: `task-${Date.now()}`,
      type,
      status: 'pending',
      description,
      result: params,
      createdAt: new Date().toISOString(),
    };
  }

  async learnFromTrade(tradeData: Record<string, unknown>): Promise<{ analysis: string; patterns: string[] }> {
    return {
      analysis: `Trade analysis stub for ${tradeData.symbol ?? 'unknown symbol'}. Norman will analyze entry/exit timing, risk/reward ratio, and pattern recognition once fully integrated.`,
      patterns: ['stub-pattern'],
    };
  }

  async getReports(): Promise<NormanReport[]> {
    return [
      {
        id: 'report-stub-1',
        title: 'Market Overview — Stub Report',
        summary: 'This is a placeholder report. Norman Agent will generate real research reports once integrated.',
        content: 'Full report content will be generated by Norman Agent.',
        symbols: ['SPY', 'QQQ'],
        createdAt: new Date().toISOString(),
      },
    ];
  }

  async getReport(id: string): Promise<NormanReport | null> {
    if (id === 'report-stub-1') {
      return {
        id: 'report-stub-1',
        title: 'Market Overview — Stub Report',
        summary: 'Placeholder report.',
        content: 'Full report content will be generated by Norman Agent.',
        symbols: ['SPY', 'QQQ'],
        createdAt: new Date().toISOString(),
      };
    }
    return null;
  }
}

export const normanAgent = new NormanAgent();
